### ISSUE TITLE
saf@mitre.org email doesnt work

### ISSUE THREAD

**Issue by opticoax747** [mitre/emasser#1]
Tried to email for more information, but email was bounced back.

Looking for use cases with this product as we are putting in POAMs for hundreds of controls and will need to change their status soon.

Can we use the REST API to do this?

Is there any how-to or demo videos on youtube?

**Comment by Bialogs** [comment]
Hi @opticoax747 Sorry to hear that. My mistake on the email. Please reach out to saf@groups.mitre.org  (saf@mitre.org was previously listed and was incorrect).

REST API should be able to support this but processing will need to be done client-side to determine how the control status should change (open->close vs. close->open). I'm assuming you have some data that supports changing a control from open->closed. So the workflow would be to align the data to a standard like NIST 800-53 control families (since most commercial scanning products don't include DISA CCI mappings), map NIST back to CCI, gather the current state of all the controls for that system, create a diff based on the new data (desired state) and what was returned from eMASS (current state), then build API requests to update accordingly.

No how-to or demo publically available but if you contact the SAF email we can send that over.
